### ISSUE TITLE
Roadmap to 2.0

### ISSUE THREAD

**Issue by AZProductions** [Avdan-OS/AvdanOS#477]
## Monorepo
- #492
- #483
- #489
- #494

## UI
- [ ] Switch to Vizia (skia branch)?
- [ ] Iconset crate as font
- [ ] Sass stylesheet with [grass macro](https://docs.rs/grass/latest/grass/macro.include.html) and `concat!(std::env!("STYLES"), "/product.scss")`

## Pipeline
- #487
- #478
- #490
